import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Calendar, ChevronDown, Info, Plus } from 'lucide-react';
import type { Hucha, Movimiento, Suscripcion } from '../../types';
import { usePrivacy } from '../../context/PrivacyContext';
import { parseMovimientoDate } from '../../hooks/useFinanceData';
import { getNextSubscriptionChargeDate } from '../../utils/subscriptions';
import { cuentaEnEstadisticas } from '../../utils/movements';
import { EmptyIllustration } from '../common/EmptyIllustration';
import { HuchaCard } from './HuchaCard';
import { ActivityList } from './ActivityList';
import { AnalyticsSection } from './AnalyticsSection';
import { FinancialOverview } from './FinancialOverview';
import { MonthlySummary } from './MonthlySummary';
import { MoreActionsMenu } from './MoreActionsMenu';
import { ServiceIcon } from './ServiceIcon';

type TimePeriod = 'este_mes' | 'mes_pasado' | 'este_anio' | 'historico';
interface ChartDatum { name: string; ingresos: number; gastos: number; }
interface DashboardViewProps { movimientos: Movimiento[]; chartMovements: Movimiento[]; huchas: Hucha[]; suscripciones: Suscripcion[]; balance: number; huchaMonthlyBudgets: Record<string, number>; chartData: ChartDatum[]; onUpdateConcepto: (id: string, concepto: string) => void; onConvert: (m: Movimiento) => void; onLink: (m: Movimiento) => void; onUnlink: (m: Movimiento) => void; onChangeHucha: (m: Movimiento, id: string) => void; onDeleteMovimiento: (m: Movimiento) => void; onSubsanar?: (h: Hucha) => void; onRevertirDeuda?: (h: Hucha) => void; onOpenHuchaModal: (h: Hucha | null) => void; onDeleteHucha: (h: Hucha) => void; onOpenTransferModal: () => void; onOpenHistoryModal: () => void; onOpenManualMovimientoModal: () => void; onOpenCalendar?: () => void; }

export const DashboardView: React.FC<DashboardViewProps> = (props) => {
  const { isLocked, formatCurrency } = usePrivacy(); const [period, setPeriod] = useState<TimePeriod>('historico'); const [periodOpen, setPeriodOpen] = useState(false); const [actionsOpen, setActionsOpen] = useState(false); const periodRef = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!periodOpen) return; const onPointerDown = (event: PointerEvent) => { if (!periodRef.current?.contains(event.target as Node)) setPeriodOpen(false); }; const onKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') setPeriodOpen(false); }; document.addEventListener('pointerdown', onPointerDown); document.addEventListener('keydown', onKeyDown); return () => { document.removeEventListener('pointerdown', onPointerDown); document.removeEventListener('keydown', onKeyDown); }; }, [periodOpen]);
  const filtered = useMemo(() => { if (period === 'historico') return props.chartMovements.filter(cuentaEnEstadisticas); const now = new Date(); return props.chartMovements.filter(m => { if (!cuentaEnEstadisticas(m)) return false; const d = parseMovimientoDate(m.fecha_operacion); if (!d) return false; if (period === 'este_mes') return d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear(); if (period === 'este_anio') return d.getFullYear() === now.getFullYear(); const previous = new Date(now.getFullYear(), now.getMonth() - 1, 1); return d.getMonth() === previous.getMonth() && d.getFullYear() === previous.getFullYear(); }); }, [props.chartMovements, period]);
  const ingresos = filtered.filter(m => m.tipo === 'ingreso').reduce((sum, m) => sum + m.importe, 0); const gastos = filtered.filter(m => m.tipo === 'gasto').reduce((sum, m) => sum + m.importe, 0);
  const periodChartData = useMemo<ChartDatum[]>(() => { const grouped = new Map<string, ChartDatum>(); filtered.forEach(movement => { const date = parseMovimientoDate(movement.fecha_operacion); if (!date) return; const key = `${date.getFullYear()}-${date.getMonth()}`; const entry = grouped.get(key) || { name: date.toLocaleDateString('es-ES', { month: 'short' }), ingresos: 0, gastos: 0 }; entry[movement.tipo === 'ingreso' ? 'ingresos' : 'gastos'] += movement.importe; grouped.set(key, entry); }); return Array.from(grouped.entries()).sort(([a], [b]) => a.localeCompare(b)).map(([, value]) => value); }, [filtered]);
  const upcoming = useMemo(() => props.suscripciones.filter(s => s.activa).map(sub => { const date = getNextSubscriptionChargeDate(sub); const daysLeft = Math.max(0, Math.ceil((date.getTime() - new Date(new Date().setHours(0, 0, 0, 0)).getTime()) / 86400000)); return { sub, date, daysLeft }; }).sort((a, b) => a.daysLeft - b.daysLeft).slice(0, 3), [props.suscripciones]);
  const periodLabel = period === 'este_mes' ? 'Este mes' : period === 'mes_pasado' ? 'Mes pasado' : period === 'este_anio' ? 'Este año' : 'Histórico';
  return <div className="space-y-6 animate-in fade-in duration-500"><header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><div className="flex items-center gap-3"><h2 className="font-title text-3xl font-bold tracking-tight text-slate-900 dark:text-white">Mi panel</h2><div ref={periodRef} className="relative"><button type="button" aria-haspopup="listbox" aria-expanded={periodOpen} onClick={() => setPeriodOpen(!periodOpen)} className="dashboard-period-button">{periodLabel}<ChevronDown size={14} /></button>{periodOpen && <div role="listbox" aria-label="Periodo" className="absolute left-0 top-[calc(100%+6px)] z-40 w-36 rounded-xl border border-slate-200 bg-white p-1 shadow-lg dark:border-slate-700 dark:bg-slate-900">{(['este_mes', 'mes_pasado', 'este_anio', 'historico'] as TimePeriod[]).map(value => <button role="option" aria-selected={period === value} type="button" key={value} onClick={() => { setPeriod(value); setPeriodOpen(false); }} className="block w-full rounded-lg px-3 py-2 text-left text-xs font-bold text-slate-700 hover:bg-indigo-50 dark:text-slate-200 dark:hover:bg-indigo-500/10">{value === 'este_mes' ? 'Este mes' : value === 'mes_pasado' ? 'Mes pasado' : value === 'este_anio' ? 'Este año' : 'Histórico'}</button>)}</div>}</div></div><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Un resumen de tu situación financiera</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={props.onOpenManualMovimientoModal} className="dashboard-primary-button"><Plus size={16} /> Añadir movimiento</button><MoreActionsMenu open={actionsOpen} onToggle={() => setActionsOpen(!actionsOpen)} onClose={() => setActionsOpen(false)} onNewHucha={() => props.onOpenHuchaModal(null)} onTransfer={props.onOpenTransferModal} onHistory={props.onOpenHistoryModal} /></div></header>
    <FinancialOverview balance={props.balance} ingresos={ingresos} gastos={gastos} />
    <section><div className="mb-3 flex items-center justify-between"><h3 className="dashboard-heading">Mis carteras</h3><span className="text-xs font-bold text-indigo-600 dark:text-indigo-400">{props.huchas.filter(h => h.activa !== false).length} activas</span></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">{props.huchas.filter(h => h.activa !== false).length ? props.huchas.filter(h => h.activa !== false).map(h => <HuchaCard key={h.id} hucha={h} onEdit={props.onOpenHuchaModal} onDelete={props.onDeleteHucha} onSubsanar={props.onSubsanar} onRevertirDeuda={props.onRevertirDeuda} />) : <div className="dashboard-empty sm:col-span-2 lg:col-span-3 xl:col-span-5"><EmptyIllustration /><p>No tienes carteras activas</p></div>}</div></section>
    <div className="grid gap-4 lg:grid-cols-3"><div className="lg:col-span-2"><AnalyticsSection chartData={periodChartData} huchas={props.huchas} suscripciones={props.suscripciones} allMovimientos={filtered} /></div><section className="dashboard-surface p-5"><div className="mb-4 flex items-start justify-between"><div className="flex items-center gap-3"><span className="dashboard-icon bg-indigo-50 text-indigo-600 dark:bg-indigo-500/10"><Calendar size={18} /></span><div><h3 className="dashboard-heading">Próximos cargos</h3><p className="dashboard-subtitle">Movimientos programados</p></div></div><button type="button" onClick={props.onOpenCalendar} className="text-[11px] font-bold text-indigo-600 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 dark:text-indigo-400">Ver calendario</button></div>{upcoming.length ? <div className="divide-y divide-slate-100 dark:divide-slate-800">{upcoming.map(({ sub, date, daysLeft }) => <div key={sub.id} className="flex items-center gap-3 py-3"><ServiceIcon name={sub.nombre} color={sub.color} /><div className="min-w-0 flex-1"><p className="truncate text-xs font-extrabold text-slate-800 dark:text-white">{sub.nombre}</p><p className="text-[11px] text-slate-500">Vence en <span className={daysLeft <= 3 ? 'font-bold text-amber-600' : 'font-bold text-slate-700 dark:text-slate-300'}>{daysLeft} {daysLeft === 1 ? 'día' : 'días'}</span> · {date.toLocaleDateString('es-ES', { day: 'numeric', month: 'short' })}</p></div><span className="text-xs font-black tabular-nums text-slate-900 dark:text-white">{isLocked ? '•• €' : formatCurrency(sub.mi_parte ?? sub.importe)}</span></div>)}</div> : <div className="dashboard-empty"><p>No hay cargos próximos</p></div>}{upcoming.length > 0 && <div className="mt-3 flex gap-2 rounded-xl bg-indigo-50 p-3 text-[11px] text-indigo-700 dark:bg-indigo-500/10 dark:text-indigo-300"><Info size={14} className="shrink-0" /> Las fechas se calculan desde tus suscripciones activas.</div>}</section></div>
    <div className="grid gap-4 lg:grid-cols-3"><div className="lg:col-span-2"><ActivityList movimientos={props.movimientos} allMovimientos={props.chartMovements} huchas={props.huchas} huchaMonthlyBudgets={props.huchaMonthlyBudgets} onUpdateConcepto={props.onUpdateConcepto} onConvert={props.onConvert} onLink={props.onLink} onUnlink={props.onUnlink} onChangeHucha={props.onChangeHucha} onDeleteMovimiento={props.onDeleteMovimiento} /></div><MonthlySummary movimientos={props.chartMovements} /></div>
  </div>;
};
