import React from 'react';
import { CheckCircle, CreditCard, Edit3, Lock, PiggyBank, Trash2, User, Wallet, WalletCards } from 'lucide-react';
import { CountUp } from '../common/CountUp';
import { type Hucha } from '../../types';
import { usePrivacy } from '../../context/PrivacyContext';

interface HuchaCardProps { hucha: Hucha; onEdit: (hucha: Hucha) => void; onDelete: (hucha: Hucha) => void; onSubsanar?: (hucha: Hucha) => void; onRevertirDeuda?: (hucha: Hucha) => void; }
const normalizeHuchaName = (name: string) => name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
const renderHuchaIcon = (hucha: Hucha) => { const name = normalizeHuchaName(hucha.nombre); if (hucha.es_suscripciones || name.includes('suscrip')) return <CreditCard size={18} />; if (hucha.es_metalico || name.includes('efectivo') || name.includes('metalico')) return <Wallet size={18} />; if (name.includes('personal')) return <User size={18} />; if (name.includes('intocable')) return <Lock size={18} />; if (name.includes('ahorro') || hucha.objetivo) return <PiggyBank size={18} />; return <WalletCards size={18} />; };

export const HuchaCard: React.FC<HuchaCardProps> = ({ hucha, onEdit, onDelete, onSubsanar, onRevertirDeuda }) => {
  const { isLocked, formatCurrency } = usePrivacy(); const hasGoal = Boolean(hucha.objetivo && hucha.objetivo > 0); const full = hasGoal && hucha.saldo_acumulado >= (hucha.objetivo || 0); const percent = hasGoal ? Math.min(100, Math.max(0, Math.round((hucha.saldo_acumulado / (hucha.objetivo || 1)) * 100))) : 0;
  const rule = hucha.tipo_aportacion === 'porcentaje' ? `${hucha.valor_aportacion}%` : hucha.tipo_aportacion === 'flat' ? (isLocked ? '•• €' : `${hucha.valor_aportacion} €`) : 'Resto';
  return <article className="dashboard-surface group p-4 transition-shadow hover:shadow-md"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><span className="dashboard-icon bg-indigo-50 text-indigo-600 dark:bg-indigo-500/10">{renderHuchaIcon(hucha)}</span><div className="min-w-0"><h4 className="truncate text-sm font-extrabold text-slate-900 dark:text-white">{hucha.nombre}</h4><p className="mt-0.5 text-[11px] text-slate-500 dark:text-slate-400">Regla: {rule}</p></div></div><div className="flex shrink-0 gap-1 opacity-100 sm:opacity-0 sm:transition-opacity sm:group-hover:opacity-100"><button type="button" aria-label={`Editar ${hucha.nombre}`} onClick={() => onEdit(hucha)} className="dashboard-icon-button"><Edit3 size={14} /></button><button type="button" aria-label={`Eliminar ${hucha.nombre}`} onClick={() => onDelete(hucha)} className="dashboard-icon-button hover:text-rose-500"><Trash2 size={14} /></button></div></div><div className="mt-5 flex items-end justify-between gap-3"><div><p className={`text-xl font-black tabular-nums ${hucha.saldo_acumulado < 0 ? 'text-rose-500' : 'text-slate-900 dark:text-white'}`}>{isLocked ? '•••• €' : <CountUp end={hucha.saldo_acumulado} decimals={2} decimal="," separator="." suffix=" €" preserveValue duration={1} />}</p>{hasGoal && <p className="mt-1 text-[11px] text-slate-500 dark:text-slate-400">Objetivo: {isLocked ? '•• €' : <CountUp end={hucha.objetivo || 0} decimals={2} decimal="," separator="." suffix=" €" preserveValue duration={1} />}</p>}</div>{full && <span className="flex items-center gap-1 text-[11px] font-bold text-emerald-600"><CheckCircle size={14} /> Completa</span>}</div>{hasGoal && <div className="mt-3 flex items-center gap-2"><div className="h-1.5 flex-1 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-indigo-500 transition-[width] duration-500" style={{ width: `${percent}%` }} /></div><span className="w-8 text-right text-[11px] font-bold text-slate-500">{isLocked ? <Lock size={12} className="ml-auto" /> : `${percent}%`}</span></div>}{(hucha.deuda_pendiente || 0) > 0 && <div className="mt-3 flex items-center justify-between text-[11px] font-bold text-rose-500">Deuda: {isLocked ? '•• €' : formatCurrency(hucha.deuda_pendiente || 0)}{onRevertirDeuda && <button type="button" onClick={() => onRevertirDeuda(hucha)} className="underline underline-offset-2">Revertir</button>}</div>}{hucha.saldo_acumulado < (hucha.subsanar_hasta || 0) && onSubsanar && <button type="button" onClick={() => onSubsanar(hucha)} className="mt-3 text-[11px] font-bold text-rose-600 underline underline-offset-2">Subsanar deuda</button>}</article>;
};
